[package]
name = "serenity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trie-rs = "0.1"
num_enum = "*"
lazy_static = "*"
pinvec = "0.1.0"
pow_of_2 = "0.1.2"
radix_trie = "0.2"

[dev-dependencies]
test-case = "*"