[package]
name = "serenity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trie-rs = "0.1"
num_enum = "*"
lazy_static = "*"
pinvec = "0.1.0"
pow_of_2 = "0.1.2"
getopts = "0.2"
tracing = {version = "0.1.40", features = ["release_max_level_off"]}
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"

[dev-dependencies]
test-case = "*"

[profile.release]
debug = true