name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: LLVM Install
      # You may pin to the exact commit or the version.
      # uses: FreeMasen/llvm-install-action@44788e07be932efaafa703a38e259fa09b6adbd8
      uses: FreeMasen/llvm-install-action@v1.0.0
      with:
        # The version of LLVM to install
        version: 18.0.0
        # The base url for the release downloads
        base-url: https://github.com/FreeMasen/llvm-builds/releases/download
          
            
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - id: pretty-test
      name: Run cargo pretty-test
      run: |
        cargo install cargo-pretty-test
        cargo pretty-test --color=always --verbose
        echo '```text' >> $GITHUB_STEP_SUMMARY
        echo "$(cargo pretty-test --color=never)" >> $GITHUB_STEP_SUMMARY 2>&1
        echo '```' >> $GITHUB_STEP_SUMMARY
  
