name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 18.0
    - name: llvm-config
      run: llvm-config --version --bindir --libdir
    - name: Install Rust Stable
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --release --verbose
    - id: pretty-test
      name: Run cargo pretty-test
      run: |
        cargo install cargo-pretty-test
        cargo pretty-test --color=always --verbose
        echo '```text' >> $GITHUB_STEP_SUMMARY
        echo "$(cargo pretty-test --color=never)" >> $GITHUB_STEP_SUMMARY 2>&1
        echo '```' >> $GITHUB_STEP_SUMMARY
