name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - id: pretty-test
      name: Run cargo pretty-test
      run: |
        cargo install cargo-pretty-test
        cargo pretty-test --color=always --verbose
        echo '```text' >> $GITHUB_STEP_SUMMARY
        echo "$(cargo pretty-test --color=never)" >> $GITHUB_STEP_SUMMARY 2>&1
        echo '```' >> $GITHUB_STEP_SUMMARY
  
