name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup LLVM
      # You may pin to the exact commit or the version.
      # uses: ZhongRuoyu/setup-llvm@5bee61a33dd6160cb4dd652cd80d56ff3654535f
      uses: ZhongRuoyu/setup-llvm@v0.1.1
      with:
        # Version of LLVM to use
        llvm-version: 18.0          
    - name: Install Rust Stable
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --release --verbose
    - id: pretty-test
      name: Run cargo pretty-test
      run: |
        cargo install cargo-pretty-test
        cargo pretty-test --color=always --verbose
        echo '```text' >> $GITHUB_STEP_SUMMARY
        echo "$(cargo pretty-test --color=never)" >> $GITHUB_STEP_SUMMARY 2>&1
        echo '```' >> $GITHUB_STEP_SUMMARY
